name: Metrics
on:
  schedule:
    - cron: "50 * * * *"
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  pull_request: {}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_output: png
          token: ${{ secrets.METRICS_TOKEN }}
          repositories: 1000
          retries: 10
          repositories_affiliations: owner, collaborator
          base: ""
          output_action: commit
          committer_message: "[metrics] update metrics"
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          config_timezone: US/Eastern
          config_display: columns

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/isocalendar/README.md
          plugin_isocalendar: no
          plugin_isocalendar_duration: full-year

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/calendar/README.md
          plugin_calendar: yes
          plugin_calendar_limit: 0

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/achievements/README.md
          plugin_achievements: true
          plugin_achievements_ignored: automater, stargazer, forker, gister # developer, member, explorer, infographile

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
          plugin_languages: yes
          plugin _languages_limit: 0

/
